### ISSUE TITLE
ScreenEvent.BackgroundRendered not called for AbstractContainerScreen

### ISSUE THREAD

**Issue by JaisDK** [neoforged/NeoForge#1182] opened 2024-06-25 13:17 UTC
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.37-beta

**Logs:** 

**Steps to Reproduce:**
 1. Extend `AbstractContainerScreen` and call `this.renderBackground`
 2. Subscribe to `ScreenEvent.BackgroundRendered`
 3. event does not fire

**Description of issue:**
`AbstractContainerScreen` now has a `renderBackground` method preventing `Screen.renderBackground`, where the event is fired, from being called

**Comment by Spinoscythe** [comment] 2024-06-25 15:49
@JaisDK correct me if I'm wrong, but the event for container screens is `ContainerScreenEvent.Render.Background`?

**Comment by JaisDK** [comment] 2024-06-25 15:54
That would probably work. I guess in 1.20.1 they were both fired.

**Comment by ChampionAsh5357** [comment] 2024-06-25 16:14
Reopening this as it is an actual bug.

**Comment by ChampionAsh5357** [comment] 2024-06-25 16:23
And now I'm closing again since it's a duplicate of #1077! Should really pay attention more. Sorry.

**Closed as completed by ChampionAsh5357** 2024-06-25 16:23 UTC
Labels: bug, regression, 1.21
