### ISSUE TITLE
[1.21] Poison causes random knockback

### ISSUE THREAD

**Issue by FaeWulf** [neoforged/NeoForge#1173] opened 2024-06-24 11:11 UTC
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.31-beta

**Steps to Reproduce:**
 1. Give player poison effect

**Description of issue:**
In vanilla Minecraft, when you take damage from poison effect, you don't get any "knockback".
But in Neoforge it does.

https://github.com/neoforged/NeoForge/assets/20983603/6525fa43-b3d2-4511-b1b1-35afae63b14b

https://github.com/neoforged/NeoForge/assets/20983603/0a78eb1e-38ca-47c0-bd22-77cdf99a32ac

**Comment by TelepathicGrunt** [comment] 2024-06-24 11:28
Caused by https://github.com/neoforged/NeoForge/issues/1162

**Comment by sciwhiz12** [comment] 2024-06-24 11:43
Duplicate of #1162

**Closed as not planned by sciwhiz12** 2024-06-24 11:43 UTC
Labels: bug, 1.21
