### ISSUE TITLE
Address the Point of Interest system memory leak in vanilla

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#398] opened 2023-12-17 08:37 UTC
It was brought to our attention that the reason why many chunk pregenerators tend to run out of memory despite unloading the chunks that they loaded is because the POI system loads in POIs and never unloads them until game is restarted. 

This means in a heavily modded instance where chunks can have a lot more POIs around and on large servers where many players are heavily exploring, a sizable chunk of RAM may be gobbled up by POIs. Eventually, they will reach a point where all the RAM is gone and forces a server shutdown and restart to clear out the POIs. 

If Neoforge implements a fix, they will need to reach out to Lithium ports and Chunk Pregenerator mods on Forge to let them know that the POIs system is fixed and no one need any of their POIs fixes anymore. This would help reduce conflicts down the road

**Comment by TelepathicGrunt** [comment] 2023-12-17 08:42
Also it was said this was reported to Mojang before but Mojang marked the report as Won’t Fix so it falls upon mods to implement a fix. But due to many failed attempts and issue people had trying to fix this, it may be better for Modloaders to handle it instead. May be much easier with NeoForge being able to do patches directly

**Comment by sciwhiz12** [comment] 2023-12-23 06:50
Could you please link the relevant Mojira bug report here? So we have a reference for it.

**Comment by sciwhiz12** [comment] 2023-12-23 06:51
It would also be useful to have references to mods which implement fixes for this POI memory leak bug, so we can compare their approaches and see what the best approach may be.

**Comment by TelepathicGrunt** [comment] 2023-12-23 12:45
I believe the bug report is this which doesn’t seem to be closed: https://bugs.mojang.com/browse/MC-173001

@Speiger can give more info on what mods are trying to optimize POI on Forge/NeoForge if any exists.

**Comment by Speiger** [comment] 2023-12-24 00:40
@sciwhiz12 @TelepathicGrunt 
Mojang has ignored that issue report since i was not actively chasing the latest version (at least at the time of reporting).
And i no longer have that account because they don't investigate bugs unless its hard latest at all and just ask: "Please reproduce in latest otherwise its invalid" (A argument can be made that yes, it should be reported in latest or close to it but the behavior never changed and it could be easily figured out if the behavior has changed, end of my rant how much valid it is or not)

Anyways, its mainly lithium that does it. They simply implement a quicker access/not present cache.
And while i reported it to a lot of them, i am not sure if all of them have it implemented, which is fine.

The main problem also is that the reading/writing of POIs are not done on the same thread, but writing is only done on a single thread.
So in worst case they are getting a delayed result.

Also there is some caveats to deleting pois when not used/unloaded.
- Accessing pois becomes significantly slower, which is the whole point why they exists. (I would test only with HDDs here)
- You could run into a fighting system due to constant requests trying to reload them. (Performance problem too)
- Crashes due to HashMap resizes, since the implementation used is a very specific FastUtil one. 
- And a few more things that don't come out of my head instantly.

**Comment by TelepathicGrunt** [comment] 2023-12-25 14:45
Doesn’t Canary (a Lithium fork) have code regarding point of interest system or is that exclusively in official Lithium?

**Comment by Speiger** [comment] 2023-12-25 17:33
@TelepathicGrunt any lithium fork has it in it.
Canary, Rubidium, Roadrunner etc etc.
I just call them lithium because that is what they are, lithium, just named differently.

**Comment by WitherTM** [comment] 2023-12-25 19:00
Rubidium is a Sodium fork, not lithium

**Comment by Lolothepro** [comment] 2023-12-25 20:23
Radium

**Comment by Speiger** [comment] 2023-12-26 11:15
@WitherTM thank you for not giving the correct name.
like @Lolothepro said, I meant radium.

I don't keep track of all the names because it is confusing enough and I am guessing often what the actual name is.
So mistakes do happen.

**Comment by TelepathicGrunt** [comment] 2024-05-04 21:14
@Speiger Where are you seeing that the POI is memory leaking from? I tried to run a test spamming POI blocks in worldgen and then pregenned a large area of the world. But I am not seeing the PoiRecord instances increasing drastically. 
![image](https://github.com/neoforged/NeoForge/assets/40846040/0362fea0-80a6-4b7b-8bc4-ad687b8a60f6)

I was assuming the PoiManager's storage field was a probably place where the leak could be for POI but I can't seem to definitively prove it.

**Comment by Speiger** [comment] 2024-05-05 11:55
@TelepathicGrunt how many chunks are "pregen a large area" for you?
Just do a 500 chunk radius (1 million chunks and takes roughly 6 hours) and look how many pois you have and how big your ram usage is.

**Comment by Speiger** [comment] 2024-05-05 12:13
@TelepathicGrunt I just started a Pregen task and let it Pregen 25k chunks roughly (more takes simply some time)
And this is the result so far.
![javaw_KeiQXZ5g7e](https://github.com/neoforged/NeoForge/assets/2556269/e2d39aef-f4f8-46fa-a634-2d05c4f1c77e)

The "POI" info references the Map: "SectionStorage.class#storage" fields size directly. (Which is a Long2ObjectMap<Optional<PoiSection>> in this specific instance.
This number by default in vanilla will NEVER GO DOWN, even if chunks unload.

Most of these entries in the Map are Optional.empty() but if 25k spawns 500k Pois and enough of them are not Empty.
What do you think will happen if enough mods provide pois or 1 mod provides a poi that present everywhere?
Also this thought process doesn't account that this is "just the start" of the task.

This is "just" 25k chunks, or a 79 chunk radius at the moment.
For vanilla singleplayer, that's reasonable for 1 dimension.

For modded or Multiplayer servers that need a larger area that is simply a huge issue.
As it will grow out of hand.

Its the whole: "Mineshafts are causing ram overflow" all over again in 1.12.2 or older (and yes i got ton of bugreports about that topic specifically)

**Comment by TelepathicGrunt** [comment] 2024-05-05 12:21
I already have some dev code to restrict that POI storage map to 5000 but still had a leak which seems to be from the ChunkMap now with the ThreadedLevelLightEngine
![image](https://github.com/neoforged/NeoForge/assets/40846040/dff84969-6d04-4344-94b4-89a002f9ec61)

**Comment by Speiger** [comment] 2024-05-05 12:36
@TelepathicGrunt that looks like chunks weren't unloaded properly in your test.
Minecraft can only handle so many chunks being loaded at the same time before it simply gives up and doesn't load more.

Or you run out of ram before that happens...
Already had both happen to me due to writing a few bugs, but both were found before release due to the way how i test.

Edit:
From my experience that is roughly 60k chunks could be more or less.
But there could be a limit to how many active tickets can exists. Not sure.
(I ran into that specific limit in 1.19.2 not sure if that behavior still exists in 1.20.5)

**Comment by Speiger** [comment] 2024-05-05 12:55
@TelepathicGrunt just a update since we are already 40 minutes into the pregen test cycle and reached the 250 chunk radius. (or 4000 blocks)

![javaw_Cp8JVtQgwZ](https://github.com/neoforged/NeoForge/assets/2556269/d577dd8a-ceba-4b3a-914a-b6e1c1b20005)

As you can see we reached the 5 million possible Poi Instances at this point.
If a PoiSection is worth 1kb if present. That would be up to 5GB of ram.
Ofc there won't be a Poi object in every single entry, but 1.25GB just if 1/4th of them have a poi, which is a lot more likely with modded.

And a radius of 500 is 4x the amount of that.
(Ignoring that a pack also needs ram without a world existing)

I hope that clarifies my point?

**Comment by Speiger** [comment] 2024-05-05 13:01
@TelepathicGrunt oh yeah i also fixed the incompat with lithium "like" mods on my side.
I simply didn't call the right functions in maps and also implemented a [concurrent Map](https://github.com/Speiger/Primitive-Collections/blob/debug/src/main/java/speiger/src/collections/longs/maps/impl/concurrent/Long2ObjectConcurrentOpenHashMap.java) into FastUtil to make the "cleanup" a lot more stable. (And yes the bugreports gone from 2-5 every week to to 0)

So the lithium optimization issue is fixed on my side now.

(This referees to crashes only, not memory leaks)

**Comment by Speiger** [comment] 2024-05-05 13:29
Last update on this...
Half of neoforges pregen limit.
![javaw_dASsybOcT6](https://github.com/neoforged/NeoForge/assets/2556269/ecc06fac-df15-432b-af48-75fe107c78e4)

So 21-24 million instances are the max for 1 million chunks.

**Comment by TelepathicGrunt** [comment] 2024-05-05 13:31
The neoforge pregen command has a bug where I forgot to remove the force load ticket so chunks were not unloading. With the POI fix and the chunk unloading fix, memory seems steady but am going to be stress testing the command have a PR up if no more issues come up

**Comment by Speiger** [comment] 2024-05-05 13:34
@TelepathicGrunt make sure that you don't keep the cache to small since the minimum is relative to how many chunks are loaded.
And Minecraft will try to fight you till death to keep that said minimum loaded.

Also make sure that the cleanup code is within the same thread as the logic that adds entries.
Or make sure its concurrent.

**Comment by TelepathicGrunt** [comment] 2024-05-05 15:34
For anyone following. Current struggle is figuring out why the chunk task priority queue for the main queue is holding onto its task and not releasing it over time. This is causing the memory leak I am seeing now in my heap dumps
![image](https://github.com/neoforged/NeoForge/assets/40846040/4418bec9-5050-4d4d-91c7-51f5a27e0e7c)
![image](https://github.com/neoforged/NeoForge/assets/40846040/061733ea-3ed8-465f-b1fd-9850e349c49e)

**Comment by Speiger** [comment] 2024-05-05 21:06
@TelepathicGrunt that is because you need to release the EXACT same Ticket and can't be fuzzy about this.
In other words the register/release function need to return the exact same variables into the ticket... Its tricky and annoying.

Edit:
https://github.com/neoforged/NeoForge/blob/df017f811c07c2685156c165ace0cbfb3279470f/src/main/java/net/neoforged/neoforge/server/command/generation/GenerationTask.java#L210-L213

Adds a ticket instead of removing it. A derp bug.

**Closed as completed** 2024-05-11 17:49 UTC
Labels: bug, enhancement, 1.20
