### ISSUE TITLE
Potentially inverted required value in ServerStatusPing$ChannelData

### ISSUE THREAD

**Issue by pupnewfster** [neoforged/NeoForge#191] opened 2023-10-24 20:57 UTC
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.79

**Description of issue:**

I was looking at the server status ping earlier trying to figure out how to solve an issue I was running into and noticed what I believe are likely to be inverted uses of the `required` field in the `ChannelData`. Changing these had no effect on my issue as it was unrelated (and I am unsure if they ever matter beyond for code clarity).
1. Setting if the channel as [required](https://github.com/neoforged/NeoForge/blob/55133ebdb40c8e83d8d816b5bdf06c0683c48116/src/main/java/net/minecraftforge/network/NetworkRegistry.java#L176) based on if it the server accepts when the client doesn't have the mod.
2. [Filtering](https://github.com/neoforged/NeoForge/blob/55133ebdb40c8e83d8d816b5bdf06c0683c48116/src/main/java/net/minecraftforge/network/NetworkRegistry.java#L271) the list of channels that are required but missing.

Based on names and the fact that the manually created `ChannelData` for `NetworkRegistry.ABSENT` uses `false` for required, I presume that the two above things should be inverted though I am not sure if I am misunderstanding how the code is functioning. This is something that we would need to fix during a breaking change window as I believe spots 1 and 2 have to be opposites of each other so if we change both then old clients connecting to new servers or new clients connecting to old servers would have the check always be completely incorrect with regards to if something is required.

**Comment by sciwhiz12** [comment] 2023-10-31 09:41
From a `git blame` dive into the code, it seems the field was originally called `mayBeAbsent`, in [the original commit](https://github.com/neoforged/NeoForge/commit/4764136d47f63d201914c3359430cf4875356434#diff-0717077ebb85d618bdaf6bac3e50f35393a50f68e94e4f20271ab8e860492485R64) which added (back) the status ping. However, [during 1.13](https://github.com/neoforged/NeoForge/blob/be5446b91c17a3dbed880028741c430610bd59f1/src/main/java/net/minecraftforge/fml/network/FMLStatusPing.java#L88), a refactor of the class (in an effort to expose a public API) caused a rename of the field from `mayBeAbsent` to the current `required`. 

The corresponding channel-filtering check [in `NetworkRegistry` from the original commit](https://github.com/neoforged/NeoForge/commit/4764136d47f63d201914c3359430cf4875356434#diff-9f879a9717c22449e79447631d472fad798068c12e4afb8ad8a47b0290ce637dR267) remains until this day, which still inverts the originally-intended `mayBeAbsent` field (to check for a channel that may _not_ be absent), but is now incorrect due to the rename.

The check for building the channel versions [in `NetworkRegistry` from the original commit](https://github.com/neoforged/NeoForge/commit/4764136d47f63d201914c3359430cf4875356434#diff-9f879a9717c22449e79447631d472fad798068c12e4afb8ad8a47b0290ce637dR170) also remains until this day, which originally intended to mark the channel as 'may be absent' if the server accepts the `ABSENT` client version, but is now also incorrect due to the rename.

Therefore, it seems the mistake here is the rename; we either ought to rename the field from `required` to `mayBeAbsent`, or invert uses of `required` as appropriate. (We will likely need to investigate all uses of `required` in either case, to ensure they are used as intended.)

**Comment by Technici4n** [comment] 2024-02-20 14:18
Closing as this is completely gone from 1.20.4+.

**Closed as not planned by Technici4n** 2024-02-20 14:18 UTC
Labels: 1.20, cleanup, area: networking
