### ISSUE TITLE
NeoForge's effects GUI is ordered differently

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#443] opened 2023-12-29 20:41 UTC
**Minecraft Version:** 1.20.4
**NeoForge Version:** 20.4.63-beta

**Steps to Reproduce:**
Minecraft Vanilla:
 1. Generate a Minecraft world
 2. Then do that
 3. Apply all the potion effects in the game (with infinite duration)
Apply the same effects with NeoForge, and compare
OR

 1. Download and install [RestWorld](https://claritypack.com/restworld/index.html)
 2. Go to the effects zone (`/execute in minecraft:overworld run tp @s -10.33 102.25 -74.03 -128.66 29.10`)
 3. Press the "All effects" sign
 4. Redo step 3 with NeoForge

**Description of issue:**

NeoForge:
![2023-12-29_21 37 50](https://github.com/neoforged/NeoForge/assets/68275908/43a72adb-e12e-4c66-af45-ffc79dbb6470)

Vanilla:
![2023-12-29_21 38 51](https://github.com/neoforged/NeoForge/assets/68275908/9100dab7-d379-4819-9020-e27fd9099496)

As you can see in these screenshots, the "hunger" effect is positioned differently with NeoForge

**Comment by sciwhiz12** [comment] 2023-12-31 08:32
Curiously, I can replicate the bug on 20.4.63-beta, the version you indicated in your report, but not on 20.4.69-beta, which is the latest version at time of writing. Could you try it as well on the latest version?

Based on the changelog, I don't see anything of note between those versions that would change how effects are rendered. We might need to test all those versions (and a few versions before 20.4.63-beta) to see what specific version 'fixed' it.

**Comment by Lolothepro** [comment] 2023-12-31 09:56
Vanilla:
![2023-12-31_10 52 58](https://github.com/neoforged/NeoForge/assets/68275908/a7fa296e-7b91-4496-99eb-1233a8a9ab54)

NeoForge 20.4.69-beta:
![2023-12-31_10 54 07](https://github.com/neoforged/NeoForge/assets/68275908/9f20d1f6-2ab2-43e5-a1c5-291288bcab3e)

not fixed

**Comment by sciwhiz12** [comment] 2023-12-31 12:16
Okay, so I just had encountered this issue in _vanilla_ (after a bit more back-and-forth), which prompted me to make a deeper investigation. From that, I can conclude that this is _not_ a NeoForge issue -- it is the behavior of the vanilla code in certain situations.

## HUD mob effect icons rendering

When rendering the effect icons on the HUD, vanilla first sorts[^sort] the `MobEffectInstance`s (as a copy of the values from the map of `MobEffect` to `MobEffectInstances`). `MobEffectInstance` implements the `Comparable` interface, and therefore the `MobEffectInstance#compareTo` method is responsible for the ordering of effects.

That `compareTo` method has two comparison chains:
- A 'regular' chain which checks the following properties in order: the effect's 'ambience' (i.e., if it's a beacon effect), the effect's duration, and the effect's sort order (which is customizable in NF through [`IMobEffectExtension#getSortOrder`](https://github.com/neoforged/NeoForge/blob/9ae1def66048a7c7bf0231d36c2b8d88c0a917f4/src/main/java/net/neoforged/neoforge/common/extensions/IMobEffectExtension.java#L37-L39) and defaults to the effect's color, matching the vanilla behavior); and
- A 'special' chain which only checks the effect's 'ambience' and the effect's sort order, in that order.

For a comparison to use the 'regular' chain, two conditions must hold true: both effects must not be equal or larger in duration of 32147 ticks (~26m 47s; about 31 seconds subtracted from 32767 ticks), and both effects must not be ambient. If either is false, then the 'special' chain is used.

## Effect comparison in this issue's situation

Both situations presented in this issue _effectively_ use the 'special' chain:
- In the case of the second situation of the test world, checking the datapack shows the effects are applied with a duration of 1,000,000 seconds[^cmd_duration]. As that amount in ticks is well above 32147 ticks, the 'special' chain is used.
- In the case of the first situation of applying effects with infinite duration: as the infinite duration is represented by a duration of -1, the 'regular' chain applies.

  However, because both effects have the same duration (-1) and are of the same infinite duration (as indicated by a duration of -1), then the 'regular' chain is effectively reduced to the effect's ambience and the effect's sort order, which is exactly the same as the 'special' chain.

Considering the 'special' chain, there are two properties: the effect's ambience, and the effect's sort order. As both effects are non-ambient (effects applied by command can't be ambient), we shall only consider the sort order.

As stated above, the effect sort order is customizable on NeoForge, but for vanilla and stock NeoForge, the sort order is the same: the effect's color value. As can be seen in the screenshots of the issue, the problem here lies with the `minecraft:instant_health` and `minecraft:saturation` effects. 

Both effects have the same color (16262179, or `#F82423`), so therefore both effect's chains are the same! Thus, both effects are considered to be equal to each other (by the comparison code). So any change in ordering must happen _before_ the sorting, as the sorting done by Minecraft has no effect to these two effects.

## Inconsistency explained

The answer to the inconsistent ordering isn't any cause of NeoForge, but the natural consequence of runs between JVMs.

Living entity effects are stored in a map; specifically, a _hash_ map ([`HashMap`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/HashMap.html)). The order of entries of the map isn't guaranteed, therefore the order of entries within the map can change from each run of the JVM.[^maporder] This explains why the two effects (saturaion and instant health) seem to differ in their positions; which one goes first entirely depends on their ordering within the original map.

So on some runs, you might have instant health go first, and on other runs, you might have saturaion go first. This is why I was unable to replicate it on 20.4.69-beta, but @Lolothepro was able to; or how (during testing while investigating this issue deeply) I was able to replicate the 'bug' on vanilla 1.20.4.

One can check that the 'regular' chain works as intended by manually applying the two effects using `/effect give @s minecraft:saturation 6000` and `/effect give @s minecraft:instant_health 6000`, and seeing the two take over each other's position when reapplying one effect using a command (to refresh its duration).

---

As per the above explanation, the issue is not a NeoForge bug. It is a consequence of the sort code for very long mob effects, the two effects having the same color, and JVM hash inconsistencies. On that basis, I close this issue.

[^sort]: The sort is in _reverse_ order; so if a comparison says A is greater than B, then B will be leftmost in the HUD than A.
[^cmd_duration]: An interesting tidbit is that the `/effect` command duration being seconds is only true for non-instant effects (i.e., effects that aren't instant health, instant damage, and saturation). For instant effects, the input duration is taken as _ticks_.
[^maporder]: If insertion order is required to be maintained in the map, then the appropriate map type would be a linked hash map ([`LinkedHashMap`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/LinkedHashMap.html)). However, that has some caveats of its own, largely due to its additional use of a linked list to maintain ordering of its map keys.

**Closed as not planned by sciwhiz12** 2023-12-31 12:16 UTC
Labels: bug, 1.20, area: rendering

**Comment by Lolothepro** [comment] 2023-12-31 12:37
https://bugs.mojang.com/browse/MC-267697
