### ISSUE TITLE
Cant change keybinds to modifier keys like shift

### ISSUE THREAD

**Issue by horse4lunch** [neoforged/NeoForge#1287] opened 2024-07-12 07:57 UTC
Minecraft Ver 1.21
Neo Ver 21.0.78
Edit: Tested in neo 21.0.86 the bug is still present 

Try to change any key bind to shift, ctrl or alt
![Screenshot 2024-07-12 035226](https://github.com/user-attachments/assets/4e6719d5-087e-47a8-9c18-03099d1440ae)
It hangs in this half selected state I assume waiting for an additional key to be pressed with the modifier key.
![Screenshot 2024-07-12 035239](https://github.com/user-attachments/assets/7d31f08e-e8af-4f00-a0e9-0e1d43235711)
When you press done it changes the keybind to left click.

Only way it seems to edit your keybinds to these keys is with the option.txt

**Comment by starforcraft** [comment] 2024-07-12 09:17
Duplicate https://github.com/neoforged/NeoForge/issues/1278

**Comment by Matyrobbrt** [comment] 2024-07-12 15:04
Duplicate of #1278

**Closed as completed by Matyrobbrt** 2024-07-12 15:04 UTC
Labels: triage
