### ISSUE TITLE
DeferredSpawnEggItem doesn't populate its MOD_EGGS map in datagen

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#1405] opened 2024-08-01 07:38 UTC
Who's ready for a niche bug :)

Because of the way the MOD_EGGS map was designed to be populated, its call to run is never reached in a datagen run, causing the DeferredSpawnEggItem#deferredOnlyById lookup to always return null if used in datagen

Haven't looked into how this would be resolved, just putting this here before I forget

**Comment by sciwhiz12** [comment] 2024-08-04 22:22
Confirmed by way of code examination.

`DeferredSpawnEggItem#deferredOnlyById` is powered by `DeferredSpawnEggItem#TYPE_MAP`, which is populated from the `MOD_EGGS` map in the same class by a handler that runs during the common setup event. However, the common setup event does not run during datagen (the event is fired by `CommonModLoader#load`, but datagen only does `CommonModLoader#begin`), so the `TYPE_MAP` doesn't get the opportunity to be populated.

We've already had multiple instances in the past where something is setup or handled in ordinary mod loading and setup that doesn't happen in datagen due to its unique code path. In the most recent case, #1359, we forced the invocation of the default components modification event during datagen by firing the appropriate method in `RegistrationEvents`.

Perhaps it would be worth investigating if all those other actions done in `RegistrationEvents#init()` are safe for datagen, such that we instead call that method for datagen instead of only `RegistrationEvents#modifyComponents()`, and insert the handler for `TYPE_MAP` there? We could also keep that pattern for future handlers too when applicable, to avoid more datagen-specialized kerfuffles.

**Comment by Matyrobbrt** [comment] 2024-11-09 13:04
As can be seen in the registration order report
https://github.com/neoforged/NeoForge/blob/424b600ec03d1bcd76e1db714dfa8c8abc17c3d7/src/generated/resources/reports/registry_order.json#L10-L11
entities are initialised before items and therefore the supplier is unneeded, and such, removing the deferred part (and having it be a simple utility that registers the colour handler and dispenser behaviour) would be appropriate.
However, given the fact that 1.21.3 is in a BC phase, I would recommend simply removing the class for that version (with the supplier being immediately resolved in 1.21.1 if a backport is needed) and instead registering the colour and dispenser handlers automatically for all spawn eggs if they're not already present.

**Closed as completed** 2024-11-10 14:06 UTC
Labels: bug, 1.21
