### ISSUE TITLE
[1.21.4] when Dyable Armor not dyed. it make non default color

### ISSUE THREAD

**Issue by baguchi** [neoforged/NeoForge#1734] opened 2024-12-04 09:04 UTC
**Minecraft Version:** 1.21.4
**NeoForge Version:** 21.4.2-beta

**Description of issue:**

I noticed this bug since 1.21.3. 

It happened vannila armor too(leather armor)

also happened on horse armor and wolf armor

![Image](https://github.com/user-attachments/assets/053c43cf-a8c2-42fc-9853-f097942b3f06)

**Comment by Lolothepro** [comment] 2024-12-04 09:10
duplicate of https://github.com/neoforged/NeoForge/issues/1612

**Comment by Matyrobbrt** [comment] 2024-12-04 15:14
Duplicate of #1612

**Closed as not planned by Matyrobbrt** 2024-12-04 15:14 UTC
