### ISSUE TITLE
Can Bind Modifier keys with the Not Bound keybind

### ISSUE THREAD

**Issue by Mattabase** [neoforged/NeoForge#1319] opened 2024-07-16 15:31 UTC
**Minecraft Version:** 1.21
**NeoForge Version:** 21.0.20 and beyond
**Logs:** N/A (No crash reported)
**Steps to Reproduce:**
 1. Open the game's keybind settings
 2. Attempt to set a keybind with a modifier key (e.g., Shift)
 3. Press Escape to set the keybind to "Not Bound"
 4. Observe the resulting keybind

**Description of issue:**
When attempting to set a keybind with a modifier key (such as Shift) and then pressing Escape to set the key to "Not Bound", the keybind is incorrectly set to "Shift+Not Bound" instead of just "Not Bound". This behavior prevents the proper clearing of keybinds that involve modifier keys

**Comment by starforcraft** [comment] 2024-07-18 13:36
Duplicate of https://github.com/neoforged/NeoForge/issues/1278

**Comment by XFactHD** [comment] 2024-07-18 17:00
This is not a duplicate of #1278, it's caused by something else.

**Comment by KnightMiner** [comment] 2024-07-18 18:17
The two are definitely related though, will probably be fixed in the same fix as they both stem from the root issue of the modifier key by itself waits for further input instead of allowing you to set it on its own.

**Closed as completed** 2024-07-24 07:16 UTC
Labels: triage
