### ISSUE TITLE
Dependency Overrides

### ISSUE THREAD

**Issue by castilio20** [neoforged/NeoForge#1056] opened 2024-06-03 09:58 UTC
https://github.com/QuiltMC/quilt-loader/wiki/Dependency-Overrides)](https://github.com/QuiltMC/quilt-loader/wiki/Dependency-Overrides
 If a mod lists itself as only compatible with mod B up to 1.1.x, but you know that its compatible in 1.2.1 you can override the mods dependency on mod B

**Comment by AterAnimAvis** [comment] 2024-06-03 10:08
This falls under FML
Duplicate of https://github.com/neoforged/FancyModLoader/issues/52

**Closed as not planned by AterAnimAvis** 2024-06-03 10:08 UTC
Labels: enhancement
