### ISSUE TITLE
With F8thful, NeoForge doesn't render blocks correctly, which causes some mobs to float in the air.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#472] opened 2024-01-06 15:37 UTC
**NeoForge Version:** 20.4.79-beta

**Logs:** https://mclo.gs/bG0rZEU

**Steps to Reproduce:**
 1. Apply the F8thful resource pack
 2. Generate a flat world with mob spawn enabled
 3. Switch to spectator mode with F3+F4
 4. Move closer to the ground

**Description of issue:**

![2024-01-06_16 33 24](https://github.com/neoforged/NeoForge/assets/68275908/bd4ce1b0-650e-4fc8-b2e9-c3016fbb16ec)

As you can see, mobs float in the void

**Comment by KnightMiner** [comment] 2024-01-07 00:13
What does it look like in vanilla? Or at the default resource pack? To me this looks like standard mob rendering at high distance stuff, things get a bit off if too far

**Comment by Lolothepro** [comment] 2024-01-07 05:10
> What does it look like in vanilla? Or at the default resource pack? To me this looks like standard mob rendering at high distance stuff, things get a bit off if too far

No, it's not normal, with Minecraft Vanilla, all the blocks are rendered.

**Comment by sciwhiz12** [comment] 2024-01-07 05:18
Duplicate of #432

**Closed as not planned by sciwhiz12** 2024-01-07 05:18 UTC
Labels: bug, 1.20, area: rendering

**Comment by sciwhiz12** [comment] 2024-01-07 05:33
Per @XFactHD, this is just the mipmapping issue demonstrated in a different way. The cause of this situation is that at mipmapping level 4, a 8×8 texture is 0×0 (original is 8×8, level 1 is 4×4, level 2 is 2×2, level 3 is 1×1, level 4 is 0x0), so the element faces with those textures rendered at that mipmapping level are transparent.

The following are two pictures from @XFactHD demonstrating essentially the same issue. The first image is when the maximum mipmapping level is at 3; the second is when it's at 4:

| Maximum mipmapping level of **3** | Maximum mipmapping level of **4** |
|:-:|:-:|
| ![image](https://github.com/neoforged/NeoForge/assets/21304337/6aa9e479-f87a-460f-86cc-bd9cb507ec68) | ![image](https://github.com/neoforged/NeoForge/assets/21304337/105216ab-4196-4e44-9d85-f9ccc8632868) |

If you flick between the two images quickly, you'll notice how the barely-visible tops of blocks at the horizontal center of the image become transparent (and render whatever's behind them); mostly visible in the left-side of the images, but there's also an instance in the sandy area on the right and at the very right-side.

**Comment by Lolothepro** [comment] 2024-01-07 14:35
but why ```Texture minecraft:block/smithing_table_side with size 8x8 limits mip level from 4 to 3``` is in the log file
The log file says that the mipmap level has been reduced

**Comment by sciwhiz12** [comment] 2024-01-07 18:44
> but why `Texture minecraft:block/smithing_table_side with size 8x8 limits mip level from 4 to 3` is in the log file The log file says that the mipmap level has been reduced

Per the issue I linked above, NeoForge currently has a feature in which mipmapping of each texture is independent of each other -- to avoid a single mod adding a non-power-of-two or too-small texture from lowering the global mipmapping level (even to the point of disabling it).
