### ISSUE TITLE
Frame rate drops overtime in Neo-Forge

### ISSUE THREAD

**Issue by kaiserdragon217** [neoforged/NeoForge#666] opened 2024-02-27 03:34 UTC
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.173

**Logs:**  https://github.com/kaiserdragon217/Logs/tree/main

**Steps to Reproduce:**
Open up and run Minecraft with Neo forge
Create a void world 
Start up F3 menu 
Wait like 30-40 minutes

**Description of issue:**
Severe frame drops when in-game over long periods of time.
Was also posted in the #user-support in the discord at 02/24/2024 11:19 AM HST
YouTube video recording: https://youtu.be/zXgA0SqP_Q8
Logs for latest.log and debug.log were large in size and could not fit in git hub gist

**System specs**
CPU: Ryzen 7 5800X
GPU: Radeon RX 6900XT
Memory: 80 gigs of DDR4 3200mhz ram
OS: Windows 10

screenshot below is at around a minute after loading in the void world with 1 piece of bedrock
![screenshot1](https://github.com/neoforged/NeoForge/assets/45612683/c336f0a2-ff95-462c-88c9-b0ce5999489a)

screenshot below is around 47 minutes after loading in
![screenshot2](https://github.com/neoforged/NeoForge/assets/45612683/278fc2d0-18f9-478b-a76b-76e88b45bcc9)

**Comment by Shadows-of-Fire** [comment] 2024-02-27 04:29
Please provide a profiler report (spark or similar) for the issue so hot code paths can be addressed.  Game logs typically do not contain information relevant to rendering performance.

**Comment by kaiserdragon217** [comment] 2024-02-27 06:14
[2024-02-26_20_04_48-New World-1_20_4.zip](https://github.com/neoforged/NeoForge/files/14415160/2024-02-26_20_04_48-New.World-1_20_4.zip)

Here is the profiler report I got when doing F3+L

**Comment by XFactHD** [comment] 2024-02-28 03:54
That profiler report unfortunately only provides a rough hint where the issue is. Since Spark doesn't exist (yet?) for NeoForge 1.20.4, please try profiling this with [VisualVM](https://visualvm.github.io/), that should provide more detailed information.

**Comment by covers1624** [comment] 2024-02-28 05:14
I have been unable to reproduce this issue on Linux. My gut feeling is this may be a driver/external software bug.

Test was performed in a fresh void world, default MC settings, except turning off music.

During the entire test, I was getting 1400FPS, with no changes over time to the frame time graph.

Do you have any of the fancy AMD driver features turned on? Low latency/frame gen/etc?

Specific test environment used:
CPU: Ryzen 9 5950x
GPU: RTX 3080ti
Drivers: NVIDIA 545.29.06
OS/Kernel: ArchLinux, 6.7.5-arch1-1
Launcher: Prism

**Comment by TheAGamePlayer** [comment] 2024-02-28 08:42
I have had this same issue a couple days ago when I was playing a world with Kaiser, it worked perfectly fine on my Fedora Linux Distro dev environment, but when I switch over to Windows 11 the issue happened. When I went to reproduce the bug today to submit my log and profiler, It magically worked fine. Low latency and frame gen wasn't even considered when I was already running the game above 300 fps, and AFMF doesn't support OpenGL anyways. I will attempt to reproduce the scenario on my end again.

**Comment by TheAGamePlayer** [comment] 2024-02-28 09:31
Deleting everything in my .minecraft and reinstalling NeoForge to the latest version (20.4.188) has caused the issue to return. Attempting to use the profiler results in Minecraft freezing upon closing. Will keep trying until I'm successful.
CPU: Ryzen 9 7900X
GPU: Rx 7900 XTX
Drivers: Adrenalin 24.2.1
OS: Windows 11
Launcher: Vanilla
My mod's dev environment in eclipse runs on Fedora 39, 6.7.5-200.fc39.x86_64 without this issue.

**Comment by kaiserdragon217** [comment] 2024-02-28 09:44
This is what I get when trying to use the VisualVM profiler they exported as .nps files : https://github.com/kaiserdragon217/VisualVM-CPU-and-Memory-profiler-snapshot/tree/main 
 I was also able to get a thread dump posted here: https://gist.github.com/kaiserdragon217/76498e596eec8528765cd5504c894bd6

It is not a Driver bug because I just did an update and it is still happening, I do not have any amd special features active.
Currently using AMD adrenaline 24.2.1 as well.

**Comment by Shadows-of-Fire** [comment] 2024-03-03 23:18
Your NPS screenshot shows that the expensive calls are the result of logging substantial amount of GL debug messages. The FPS drop is from the logging, but the cause is whatever is triggering a high-severity API error. Since it is specific to AMD cards on the windows platform, it is unlikely to be an actual problematic API call, and is instead a driver bug.

> It is not a Driver bug because I just did an update and it is still happening,  

Just updating a driver does not mean a particular issue was fixed.

![](https://i.imgur.com/T6vpgOm.png)

If there are no actual rendering errors present, and the error is being logged incorrectly for some reason, you could apply a workaround: going into your `options.txt` file and changing `glDebugVerbosity:1` to `glDebugVerbosity:0` will disable all debug logging.

**Comment by TheAGamePlayer** [comment] 2024-03-04 22:33
It is something to note that while Forge produces the same error messages, it does not experience the same performance drops currently existing in NeoForge.

**Comment by TheAGamePlayer** [comment] 2024-04-08 23:13
May I propose a warning screen giving players the option to set glDebugVerbosity to 0 on initial startup till this bug is properly fixed? I feel like it would save many the headache if they do not understand what is going on.

**Comment by TelepathicGrunt** [comment] 2024-07-25 01:23
Closing issue report as we are not able to reproduce the issue and feel this is more of a system issue for the 2 reporter's specific systems. Likely a bad driver. If this issue comes up again with a reproducible case on a neo maintainer's system, then we would be able to dig more and do a proper fix.

**Closed as completed by TelepathicGrunt** 2024-07-25 01:23 UTC
Labels: bug, area: rendering, triage

**Comment by konghuanyueli** [comment] 2025-01-01 10:14
Hello, just a few days ago, my friend encountered the same issue with version 1.21.1 Neoforge 21.1.92. May I ask if the original poster has resolved the problem?

**Comment by TheAGamePlayer** [comment] 2025-02-05 04:30
Sorry for not noticing this sooner, DDU & AMD Cleanup Utility does not work to fix this issue, a fresh install of Windows 10/11 was required. It seems Windows did something to AMD drivers that seemed to cause this issue, but I'm not 100% certain.
