### ISSUE TITLE
error on minecraft:register packets received

### ISSUE THREAD

**Issue by fayer3** [neoforged/NeoForge#533] opened 2024-01-17 17:12 UTC
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.111-beta

**Logs:** https://mclo.gs/ExVLM6c

**Steps to Reproduce:**
 1. host a spigot/paper server with a plugin that want's to register a channel
 2. in this case it's the [vivecraft spigot extension](https://github.com/jrbudda/Vivecraft_Spigot_Extensions/releases), it want's to register the `vivecraft:data` channel
 3. try to connect with a neoforge client
 4. get error about not enough bytes

**Description of issue:**
connecting to a server that sends a `minecraft:register` packet throws an error, and disconnects.

![grafik](https://github.com/neoforged/NeoForge/assets/8282299/c46802af-8f9a-4441-8197-7668fce21c8a)

**Comment by Matyrobbrt** [comment] 2024-01-17 17:18
Duplicate of #450

**Closed as completed** 2024-01-17 17:18 UTC
Labels: triage

**Comment by fayer3** [comment] 2024-01-17 17:21
ah, sorry
