### ISSUE TITLE
Minecraft crashes after a few miliseconds but only with neo forge modloader

### ISSUE THREAD

**Issue by 05Narwhal** [neoforged/NeoForge#1441] opened 2024-08-11 16:51 UTC
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.167

**Logs:** Log: _<redacted by @sciwhiz12>_

**Description of issue:**
So whenever I try to launch minecraft on NeoForge my game crashes imidiatelywith a error code of 1. It says its a java runtime issue. I tried a bunch of other java versions like 17, 18, 22, 21, 8 and none of them worked. But when I launch minecraft using Fabric everything works perfectly. I now the modpack is stable because 3 of my friends have the same set of mods and there mc launches fine. I updated my CPU and GPU drivers and nothing changed. Please fix this as fast as you can. 
Thank you,

Julian

**Comment by embeddedt** [comment] 2024-08-11 17:46
The crash is occurring in your GPU driver; I doubt that is something we can fix. I would recommend double-checking you are actually on the latest driver version, and if you are, try rolling back a couple versions.

**Comment by 05Narwhal** [comment] 2024-08-12 19:14
I tried that yet still have the same issue. But fabric works fine.

**Comment by Zelioth** [comment] 2024-08-15 12:58
I can't explain yet why but I seem to be having the same issue. Developing my mod pack randomly my profile for the pack will not launch and crash on startup with error code 1. It won't even start loading. it just closes. I have had the issue in NeoForge 21.1.12 but it started to happen every time I update over that version. 

At first I thought it was a mod. I disabled all mods and it still crashes with nothing active. The logs don't report any information. I have a RTX 4090 GPU and the drivers are completely updated. 
[debug.log](https://github.com/user-attachments/files/16625348/debug.log)
[latest.log](https://github.com/user-attachments/files/16625350/latest.log)


I posted logs but this is all the information that shows up in them. To fix the issue I have to completely delete the profile and create a new one, Move over the mods folder and config and it works perfect for a few launches. If i update NeoForge or use it a few times that crash issue happens again.

**Comment by Zelioth** [comment] 2024-08-15 13:05
I have a profile that is doing this after working just fine. AFTER creating a new profile on NeoForge 21.1.12 the game works fine again. This log contains a mod issue but besides that it is attempting to launch and getting much further. 
[latest.log](https://github.com/user-attachments/files/16625417/latest.log)
[debug.log](https://github.com/user-attachments/files/16625420/debug.log)

**Comment by Zelioth** [comment] 2024-08-15 13:23
I have managed to somehow create a curseforge profile that has the issue. I created a new profile, made sure it crashed on startup and that it was the same issue no matter what version of NeoForge I set it too. I created to profile then deleted the original. I imported the profile I had saved and confirmed it crashes on startup with the same issue 

AGAIN this profile worked perfect then randomly stopped working with no change to files. I also found this issue is created when updating NeoForge past 21.1.8

[Friends United 2.1-CRASHING ON STARTUP.zip](https://github.com/user-attachments/files/16625554/Friends.United.2.1-CRASHING.ON.STARTUP.zip)

**Comment by Zelioth** [comment] 2024-08-16 17:09
UPDATE. Deleting the options.txt file fixes the issue. It is some sort of error in the options.txt file

**Comment by sciwhiz12** [comment] 2024-08-17 05:50
> It is some sort of error in the options.txt file

If that is the case, we'd need that erroneous `options.txt` to be able to investigate the issue.

**Comment by Zelioth** [comment] 2024-08-17 05:51
I provided the profile that contains that options.txt

**Comment by Zelioth** [comment] 2024-08-17 05:53
[options.txt](https://github.com/user-attachments/files/16643634/options.txt)

just in case here is the options.txt that when deleted allows the client to work fine

**Comment by sciwhiz12** [comment] 2024-08-17 06:07
> I provided the profile that contains that options.txt

Ah whoops, I missed that. Sorry. With your profile, I can reproduce the crash, and checking the error log (which I should've really done first) shows that the immediate crash is caused by duplicate lines in the `options.txt` file.

Particularly, the following lines indicated in red are duplicates of the three lines before them:

```diff
@@ -353,9 +353,6 @@ key_key.entityculling.toggle:key.keyboard.unknown
 key_key.stellaris.rocket_start:key.keyboard.space
 key_key.stellaris.freeze_planet_menu:key.keyboard.x
 key_key.stellaris.jetsuit_mode:key.keyboard.v
-key_key.stellaris.rocket_start:key.keyboard.space
-key_key.stellaris.freeze_planet_menu:key.keyboard.x
-key_key.stellaris.jetsuit_mode:key.keyboard.v
 key_pneumaticcraft.armor.upgrade.fall_protection:key.keyboard.unknown
 key_pneumaticcraft.armor.upgrade.jet_boots.module.hover:key.keyboard.unknown
 key_pneumaticcraft.armor.upgrade.stomp:key.keyboard.unknown
```

Removing those lines or deleting the `options.txt` file to regenerate it fixes the issue. (However, the given profile still crashes on my machine due to an unrelated issue.) NeoForge itself does not mess with the writing of keymappings, to my knowledge, so this issue is caused by something else (possibly by the Stellaris mod?).

---

However, that issue, @Zelioth, is different from this issue author's problem, as the issue author seems to be encountering some sort of error with the graphics driver causing a JVM crash. 

In the future, please first try to raise your issues in the NeoForged Discord server when asking for support. (The people in the Discord server will tell you to file an issue if appropriate.)

**Comment by Zelioth** [comment] 2024-08-17 06:10
understood. I looked over the issue reports and a few other things and seen this one assuming it was similar issue due to the client reporting the same Error 1 issue when crashing on my machine. I disabled all mods and it was still crashing so that is why  I assumed it was something more NeoForge related in the Options.txt.

**Comment by sciwhiz12** [comment] 2024-08-17 15:33
@05Narwhal, without more information outside of the provided JVM crash log, we cannot diagnose any part of your issue outside of inferring it was likely caused by an interaction with your graphics driver.

We wouldneed more information on your setup to try diagnose any part of this issue: log files, if you can replicate the crash on vanilla Minecraft or on no-mods NeoForge, and so on. I highly recommend you to go to the [official Discord server](https://discord.neoforged.net) and ask for suppport there instead of on this issue tracker, because we reserve this issue tracker for final bug reports.

Additionally, I've taken the step of redacting your log file from your initial post because that JVM crash log contains the full command-line of your Minecraft instance, due to sensitive information contained therein. 

I've been advised that the sensitive information had already expired when you posted the log file, so no action needs to be taken. However, I must strongly recommend to **refrain from posting any `hs_err_pid_<>` files to people you do not trust (which includes the public internet)**.

I'll be closing this issue; again, please head to the Discord server for more support.

**Closed as not planned by sciwhiz12** 2024-08-17 15:33 UTC
Labels: bug, triage, 1.21
