### ISSUE TITLE
1.20.5 - Crash with mod that adds new ores

### ISSUE THREAD

**Issue by kwpugh** [neoforged/NeoForge#898] opened 2024-05-01 03:39 UTC
Minecraft: 1.20.5
Neo: 20.5.21-beta

crash report: https://gist.github.com/kwpugh/350eca2fd1d22185cc3b9f555e1ba96c

**Steps to Reproduce:**
 1. load a mod that adds ores to worldgen
 2. load the world the first time, then exit
 3. re-load the world and move towards a new chuck
 4. crash!

I encountered a crash in Fabric 1.20.5-rc1 that exhibited the same behavior with ore gen
https://github.com/FabricMC/fabric/issues/3719

I don't know if it is the same, but it feels similar.  It took the fabric devs a bit of time to figure it out, so I include it just in case.

I also tested another mod that is out for 1.20.5 and adds ores, it crashes as well.

If you need any more info from me, let me know.

**Comment by Technici4n** [comment] 2024-05-01 06:41
Duplicate of https://github.com/neoforged/NeoForge/issues/868

**Closed as not planned by Technici4n** 2024-05-01 06:41 UTC
Labels: triage
