### ISSUE TITLE
Server List Ping not giving a response

### ISSUE THREAD

**Issue by Joyfulasteroid** [neoforged/NeoForge#1232] opened 2024-07-04 18:11 UTC
**1.21:** {Minecraft version}

**21.0.51-beta:** {NeoForge version. *Version number, not latest/rb*}

**No Logs could be found** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Download ATM10 modpack
 2. Download server files and install server
 3. Try to connect

**Description of issue:**
Tried to do this with no mods on the server and i still recieve no ping. Vanilla client can see the ping from the server

**Comment by Joyfulasteroid** [comment] 2024-07-04 18:42
Enigmatica 10 - E10 also has this issue but that is on NeoForge 21.0.42

**Comment by RubenPX** [comment] 2024-07-04 18:57
Same here.Not working servers using installer

**Comment by sciwhiz12** [comment] 2024-07-04 21:16
Cannot reproduce on 21.0.54, .51, and .42 without any mods and using a locally hosted 21.0.54 NeoForge server. Added an entry on the server list for `localhost`, and the server shows up properly on the multiplayer screen. 

Added an externally hosted private server which runs NeoForge but a different Minecraft version also works -- it shows up, and it remarks properly that the server is running a different Minecraft version.

Testing on All the Mods 10 reveals the issue does exist when using that pack (using the same locally hosted server as above), which means the issue is caused by a mod rather than NeoForge. Someone will need to search for the problematic mod and report the issue to the mod author.

As the issue is not caused by NeoForge, I'm closing the issue.

**Closed as not planned by sciwhiz12** 2024-07-04 21:16 UTC
Labels: bug, triage, 1.21

**Comment by Joyfulasteroid** [comment] 2024-07-05 21:50
Confirmed this as the No-Chat-Report mod which is currently at "NoChatReports-NEOFORGE-1.21-v2.8.0" for future reference if anyone goes looking for it.

Sciwhiz12 thank you for your help finding the cause
